### ISSUE TITLE
paper-behaviors focus state issue 

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-behaviors#11]
Currently, the keyboard focus is tough to see on the Hello World buttons, as it's only implemented as a shadow animation. It is not visually clear to me which button has focus, since the animation is quick and the shadow is light. 

The focus state for the radio button is fine though. The large gray circle is helpful.

**Comment by blasten** [comment]
There's a button in the demo, @cdata is working on the buttons.

**Comment by blasten** [comment]
https://github.com/PolymerElements/paper-behaviors/pull/24 is addressing the keyboard focus issue

**Comment by lpalmaro** [comment]
Great. If you don't mind, simply close out this issue once that is
implemented and we can take a look.

**Comment by lpalmaro** [comment]
Quick follow up on this. I just tested with JAWS on Firefox. On Firefox, I can't seem to activate the radio button with the keyboard. This works on Chrome on Windows, as well as other OSes and browser combos. Any idea why this might not be working in FF?

**Comment by notwaldorf** [comment]
I don't think this is an issue anymore. Please re-open if its still reproducible
