### ISSUE TITLE
`PaperRadioButtonBehaviour` refactoring

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/paper-behaviors#22]
- it should have the `checked` state that `paper-checkbox`/`paper-radio-button`/`paper-toggle-button` all share
- the inky behaviour which `paper-icon-button` now uses should be split out.

/cc @cdata

**Comment by cdata** [comment]
@notwaldorf this isn't changed by any of our eleventh hour updates to the behaviors, is it?

**Comment by notwaldorf** [comment]
Nope. We punted on it pretty swiftly. (`paper-icon-button` still includes something called `paper-radio-button-behaviour` which looks weird at first)

**Comment by notwaldorf** [comment]
All of this has been fixed.
