### ISSUE TITLE
Use of private `_rippleContainer` in demo

### ISSUE THREAD

**Issue by zoechi** [PolymerElements/paper-behaviors#49]
https://github.com/PolymerElements/paper-behaviors/blob/7a674a3635fcb6db4842d16d3fd768ab07d638a8/demo/paper-radio-button.html#L112

I'm working on porting the demos to Dart Polymer, but this private field isn't available in Dart.
IMHO if it is private it shouldn't be used in the demo, if it's ok to use it it shouldn't be private.

**Comment by keanulee** [comment]
Hi @zoechi,

We actually use single underscore to denote protected properties/methods. The `_rippleContainer` property is used in `PaperRippleBehavior`, included by `PaperInkyFocusBehavior`, `PaperCheckedElementBehavior`, which is used by the demo element.

**Comment by zoechi** [comment]
I Dart the `_` in the name makes it private and in Dart this is enforced. I try to get this fixed in the Dart wrapper. Thanks a lot for the info!
