### ISSUE TITLE
Add documentation for the PaperCheckedElementBehavior

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-behaviors#51]
In this link not appear the correct documentation:
https://elements.polymer-project.org/elements/paper-behaviors?active=Polymer.PaperCheckedElementBehavior

**Comment by notwaldorf** [comment]
Why do you say that link is showing the wrong docs? I see all the aggregated properties, events etc. from the two behaviours that make up that behaviour (`PaperInkyFocusBehavior` and `IronCheckedElementBehavior`).

**Comment by abdonrd** [comment]
Hmmm now it`s perfect! 3 days ago was wrong.
Closed! :)

**Comment by notwaldorf** [comment]
Whew! 🎉
