### ISSUE TITLE
Mixins?

### ISSUE THREAD

**Issue by iSuslov** [PolymerElements/paper-behaviors#81]
It's not clear how to use this behaviours in 2.0 version. Do you provide mixins for that?

**Comment by TimvdLippe** [comment]
You can use the 1.0 behaviors as mixins with `Polymer.mixinBehaviors`. For more information see https://www.polymer-project.org/2.0/docs/upgrade#mixins and the API documentation: https://www.polymer-project.org/2.0/docs/api/#function-Polymer.mixinBehaviors
