### ISSUE TITLE
import paper-ripple-behavior on paper-checked-element-behavior.html

### ISSUE THREAD

**Issue by jay8t6** [PolymerElements/paper-behaviors#87]
When building the polymer code, it doesn't import the ripple behavior, and causing a runtime issue this.hasRipple() is not a function. But when I import paper-ripple-behavior on paper-checked-element-behavior.html, it works fine.

**Comment by keanulee** [comment]
`PaperInkyFocusBehavior` includes `PaperRippleBehavior`, so I don't see why this is needed https://github.com/PolymerElements/paper-behaviors/blob/master/paper-inky-focus-behavior.html#L48. Closing issue.
